name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: pwd
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t myimage -f Dockerfile.dev .
      - run: docker run -e CI=true myimage npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

 
